wechat:
  api:
    url:
      pay:
        notify: 'https://uat.mall-server.bsxkj.com/client/wechat/notify/pay'
      refund:
        notify: 'https://uat.mall-server.bsxkj.com/client/wechat/notify/refund'
       
       
