wechat:
  api:
    url:
      pay:
        notify: 'https://mall-server.dbjiaju.cn/client/wechat/notify/pay'
      refund:
        notify: 'https://mall-server.dbjiaju.cn/client/wechat/notify/refund'
       
       
