spring.application.name: mall-web
spring.session.redis.namespace: session:${spring.application.name}
spring:
  datasource:
    table:
      prefix: 

user.type.name: client

cookie.token.name: token

alipay:
  api:
    public.key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq90eOhXPGSiVhd74RxTqo90XAwdX5v1A/0JbrpWzh895UkeNW6eDx0Ot9D98ZNXYb1f+3KHfOa0rVsiSDdnH3MH7aDxaTxzoR9YDYll3gUVIyVEA4qdBRAJz09nBmsR+2DgEng3I2PZAEbwgS4ZDrzMTyJOpsFKyy+8OtGlBeEznZAvBSOgITM7a6ihzbxBm41+0cNbL2o05i2Sbq5aMNyIn3RswTa911nzQ6tMe/T774iwYnZ42RpzPF7Lj6i5gOTmY5IhZzA8PhJJ+38IOsrjyaqNJKAuUjgZFEw5FkRPkE+3Z1O3N2H+qV964glhCaF44DPwnyWQdFyLjd5KA5wIDAQAB
    url:
      gateway: 'https://openapi.alipay.com/gateway.do'

wechat:
  user:
    url:
      authorization: 'https://open.weixin.qq.com/connect/oauth2/authorize?appid=%s&redirect_uri=%s&response_type=code&scope=snsapi_userinfo&state=%s#wechat_redirect'
      access_token: 'https://api.weixin.qq.com/sns/oauth2/access_token?appid=%s&secret=%s&code=%s&grant_type=authorization_code'
      userinfo: 'https://api.weixin.qq.com/sns/userinfo?access_token=%s&openid=%s&lang=zh_CN'
  api:
    url:
      access_token: 'https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s'
      js: 'https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=%s&type=jsapi'
      file: 'http://file.api.weixin.qq.com/cgi-bin/media/get?access_token=%s&media_id=%s'
