spring.application.name: mall-web
spring.session.redis.namespace: session:${spring.application.name}
spring:
  datasource:
    table:
      prefix: 

user.type.name: client

cookie.token.name: token

wechat:
  user:
    url:
      authorization: 'https://open.weixin.qq.com/connect/oauth2/authorize?appid=%s&redirect_uri=%s&response_type=code&scope=snsapi_userinfo&state=%s#wechat_redirect'
      access_token: 'https://api.weixin.qq.com/sns/oauth2/access_token?appid=%s&secret=%s&code=%s&grant_type=authorization_code'
      userinfo: 'https://api.weixin.qq.com/sns/userinfo?access_token=%s&openid=%s&lang=zh_CN'
  api:
    url:
      access_token: 'https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s'
      js: 'https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=%s&type=jsapi'
      file: 'http://file.api.weixin.qq.com/cgi-bin/media/get?access_token=%s&media_id=%s'

share.image.background.path: common/client/share-info-bg.png

user.avatar.default.path: common/client/avatar.png