spring.application.name: mall-web
spring.session.redis.namespace: session:${spring.application.name}
spring:
  datasource:
    table:
      prefix: 

user.type.name: client

wechat:
  url:
    access_token: 'https://api.weixin.qq.com/sns/oauth2/access_token?appid=%s&secret=%s&code=%s&grant_type=authorization_code'
    userinfo: 'https://api.weixin.qq.com/sns/userinfo?access_token=%s&openid=%s'