server.port: 9002
#spring:
#  jpa:
#    show-sql: true
#spring.main.allow-bean-definition-overriding: true

wechat:
  api:
    url:
      pay:
        notify: 'http://localhost:9002/client/wechat/notify/pay'
      refund:
        notify: 'http://localhost:9002/client/wechat/notify/refund'

